import pandas as gh
df=gh.read_csv('StudentsPerformance (1).csv')
print(df)
print("-------------------------------------------------------------------")
print(df.isnull().sum())
print("-------------------------------------------------------------------")
print(df.describe())
print("-------------------------------------------------------------------")
print(df[df['gender'] == 'female'])
print("-------------------------------------------------------------------")
sorted_data = df.sort_values(by='race/ethnicity')
print(sorted_data)
print("-------------------------------------------------------------------")
print("Math Score Average:", df['math score'].mean())
print("Reading Score Average:", df['reading score'].mean())
print("Writing Score Average:", df['writing score'].mean())
print("-------------------------------------------------------------------")
print(df['lunch'].value_counts())
print("-------------------------------------------------------------------")
df['Average'] = df[['math score', 'reading score', 'writing score']].mean(axis=1)
print(df)
print("-------------------------------------------------------------------")
if 'math score' in df.columns:
    print("Math Score Average:", df['math score'].mean())

print("-------------------------------------------------------------------")
print(df.loc[df['Average'].idxmin()])
print("-------------------------------------------------------------------")
print(df.loc[df['Average'].idxmax()])